// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: taskengine/v1/taskengine.proto

package taskenginev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_PENDING     TaskState = 1
	TaskState_TASK_STATE_EXECUTING   TaskState = 2
	TaskState_TASK_STATE_THROTTLED   TaskState = 3
	TaskState_TASK_STATE_COMPLETED   TaskState = 4
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_PENDING",
		2: "TASK_STATE_EXECUTING",
		3: "TASK_STATE_THROTTLED",
		4: "TASK_STATE_COMPLETED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     1,
		"TASK_STATE_EXECUTING":   2,
		"TASK_STATE_THROTTLED":   3,
		"TASK_STATE_COMPLETED":   4,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_taskengine_v1_taskengine_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_taskengine_v1_taskengine_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_taskengine_v1_taskengine_proto_rawDescGZIP(), []int{0}
}

type ScheduleTaskRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId            string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                     // Identifier for ingress rate limiting
	RateLimitKey        string                 `protobuf:"bytes,3,opt,name=rate_limit_key,json=rateLimitKey,proto3" json:"rate_limit_key,omitempty"`                       // External target key for egress rate limiting (e.g. "vendor:openai", "endpoint:webhook")
	Weight              int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`                                                        // Weight / token cost for egress rate limiting (default 1)
	ScheduleTime        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=schedule_time,json=scheduleTime,proto3" json:"schedule_time,omitempty"`                         // When task should execute
	Payload             string                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`                                                       // Task payload
	RepeatIntervalNanos int64                  `protobuf:"varint,7,opt,name=repeat_interval_nanos,json=repeatIntervalNanos,proto3" json:"repeat_interval_nanos,omitempty"` // Interval for recurring tasks (optional)
	MaxRuns             int32                  `protobuf:"varint,8,opt,name=max_runs,json=maxRuns,proto3" json:"max_runs,omitempty"`                                       // Max runs for recurring tasks (0 = unlimited)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ScheduleTaskRequest) Reset() {
	*x = ScheduleTaskRequest{}
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskRequest) ProtoMessage() {}

func (x *ScheduleTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskRequest.ProtoReflect.Descriptor instead.
func (*ScheduleTaskRequest) Descriptor() ([]byte, []int) {
	return file_taskengine_v1_taskengine_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduleTaskRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ScheduleTaskRequest) GetRateLimitKey() string {
	if x != nil {
		return x.RateLimitKey
	}
	return ""
}

func (x *ScheduleTaskRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ScheduleTaskRequest) GetScheduleTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduleTime
	}
	return nil
}

func (x *ScheduleTaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ScheduleTaskRequest) GetRepeatIntervalNanos() int64 {
	if x != nil {
		return x.RepeatIntervalNanos
	}
	return 0
}

func (x *ScheduleTaskRequest) GetMaxRuns() int32 {
	if x != nil {
		return x.MaxRuns
	}
	return 0
}

type ScheduleTaskResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message               string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedNode          string                 `protobuf:"bytes,3,opt,name=assigned_node,json=assignedNode,proto3" json:"assigned_node,omitempty"`
	IngressRemainingQuota int64                  `protobuf:"varint,4,opt,name=ingress_remaining_quota,json=ingressRemainingQuota,proto3" json:"ingress_remaining_quota,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ScheduleTaskResponse) Reset() {
	*x = ScheduleTaskResponse{}
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskResponse) ProtoMessage() {}

func (x *ScheduleTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskResponse.ProtoReflect.Descriptor instead.
func (*ScheduleTaskResponse) Descriptor() ([]byte, []int) {
	return file_taskengine_v1_taskengine_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScheduleTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScheduleTaskResponse) GetAssignedNode() string {
	if x != nil {
		return x.AssignedNode
	}
	return ""
}

func (x *ScheduleTaskResponse) GetIngressRemainingQuota() int64 {
	if x != nil {
		return x.IngressRemainingQuota
	}
	return 0
}

type InspectQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectQuotaRequest) Reset() {
	*x = InspectQuotaRequest{}
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectQuotaRequest) ProtoMessage() {}

func (x *InspectQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectQuotaRequest.ProtoReflect.Descriptor instead.
func (*InspectQuotaRequest) Descriptor() ([]byte, []int) {
	return file_taskengine_v1_taskengine_proto_rawDescGZIP(), []int{2}
}

func (x *InspectQuotaRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type InspectQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Remaining     int64                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	ResetAfterMs  int64                  `protobuf:"varint,4,opt,name=reset_after_ms,json=resetAfterMs,proto3" json:"reset_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectQuotaResponse) Reset() {
	*x = InspectQuotaResponse{}
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectQuotaResponse) ProtoMessage() {}

func (x *InspectQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectQuotaResponse.ProtoReflect.Descriptor instead.
func (*InspectQuotaResponse) Descriptor() ([]byte, []int) {
	return file_taskengine_v1_taskengine_proto_rawDescGZIP(), []int{3}
}

func (x *InspectQuotaResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InspectQuotaResponse) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *InspectQuotaResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *InspectQuotaResponse) GetResetAfterMs() int64 {
	if x != nil {
		return x.ResetAfterMs
	}
	return 0
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_taskengine_v1_taskengine_proto_rawDescGZIP(), []int{4}
}

func (x *CancelTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_taskengine_v1_taskengine_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusRequest) Reset() {
	*x = GetTaskStatusRequest{}
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusRequest) ProtoMessage() {}

func (x *GetTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_taskengine_v1_taskengine_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaskStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         TaskState              `protobuf:"varint,2,opt,name=state,proto3,enum=taskengine.v1.TaskState" json:"state,omitempty"`
	AssignedNode  string                 `protobuf:"bytes,3,opt,name=assigned_node,json=assignedNode,proto3" json:"assigned_node,omitempty"`
	RunCount      int32                  `protobuf:"varint,4,opt,name=run_count,json=runCount,proto3" json:"run_count,omitempty"`
	NextRun       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"`
	LastError     string                 `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusResponse) Reset() {
	*x = GetTaskStatusResponse{}
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusResponse) ProtoMessage() {}

func (x *GetTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskengine_v1_taskengine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_taskengine_v1_taskengine_proto_rawDescGZIP(), []int{7}
}

func (x *GetTaskStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTaskStatusResponse) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *GetTaskStatusResponse) GetAssignedNode() string {
	if x != nil {
		return x.AssignedNode
	}
	return ""
}

func (x *GetTaskStatusResponse) GetRunCount() int32 {
	if x != nil {
		return x.RunCount
	}
	return 0
}

func (x *GetTaskStatusResponse) GetNextRun() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRun
	}
	return nil
}

func (x *GetTaskStatusResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

var File_taskengine_v1_taskengine_proto protoreflect.FileDescriptor

const file_taskengine_v1_taskengine_proto_rawDesc = "" +
	"\n" +
	"\x1etaskengine/v1/taskengine.proto\x12\rtaskengine.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x02\n" +
	"\x13ScheduleTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12$\n" +
	"\x0erate_limit_key\x18\x03 \x01(\tR\frateLimitKey\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x12?\n" +
	"\rschedule_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fscheduleTime\x12\x18\n" +
	"\apayload\x18\x06 \x01(\tR\apayload\x122\n" +
	"\x15repeat_interval_nanos\x18\a \x01(\x03R\x13repeatIntervalNanos\x12\x19\n" +
	"\bmax_runs\x18\b \x01(\x05R\amaxRuns\"\xa7\x01\n" +
	"\x14ScheduleTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rassigned_node\x18\x03 \x01(\tR\fassignedNode\x126\n" +
	"\x17ingress_remaining_quota\x18\x04 \x01(\x03R\x15ingressRemainingQuota\"'\n" +
	"\x13InspectQuotaRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x82\x01\n" +
	"\x14InspectQuotaResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x03R\tremaining\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12$\n" +
	"\x0ereset_after_ms\x18\x04 \x01(\x03R\fresetAfterMs\"#\n" +
	"\x11CancelTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\x14GetTaskStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xef\x01\n" +
	"\x15GetTaskStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x05state\x18\x02 \x01(\x0e2\x18.taskengine.v1.TaskStateR\x05state\x12#\n" +
	"\rassigned_node\x18\x03 \x01(\tR\fassignedNode\x12\x1b\n" +
	"\trun_count\x18\x04 \x01(\x05R\brunCount\x125\n" +
	"\bnext_run\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\anextRun\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError*\x8d\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x01\x12\x18\n" +
	"\x14TASK_STATE_EXECUTING\x10\x02\x12\x18\n" +
	"\x14TASK_STATE_THROTTLED\x10\x03\x12\x18\n" +
	"\x14TASK_STATE_COMPLETED\x10\x042\xf4\x02\n" +
	"\x11TaskEngineService\x12W\n" +
	"\fScheduleTask\x12\".taskengine.v1.ScheduleTaskRequest\x1a#.taskengine.v1.ScheduleTaskResponse\x12W\n" +
	"\fInspectQuota\x12\".taskengine.v1.InspectQuotaRequest\x1a#.taskengine.v1.InspectQuotaResponse\x12Q\n" +
	"\n" +
	"CancelTask\x12 .taskengine.v1.CancelTaskRequest\x1a!.taskengine.v1.CancelTaskResponse\x12Z\n" +
	"\rGetTaskStatus\x12#.taskengine.v1.GetTaskStatusRequest\x1a$.taskengine.v1.GetTaskStatusResponseB@Z>github.com/vnmchuo/taskengine/proto/taskengine/v1;taskenginev1b\x06proto3"

var (
	file_taskengine_v1_taskengine_proto_rawDescOnce sync.Once
	file_taskengine_v1_taskengine_proto_rawDescData []byte
)

func file_taskengine_v1_taskengine_proto_rawDescGZIP() []byte {
	file_taskengine_v1_taskengine_proto_rawDescOnce.Do(func() {
		file_taskengine_v1_taskengine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskengine_v1_taskengine_proto_rawDesc), len(file_taskengine_v1_taskengine_proto_rawDesc)))
	})
	return file_taskengine_v1_taskengine_proto_rawDescData
}

var file_taskengine_v1_taskengine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_taskengine_v1_taskengine_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_taskengine_v1_taskengine_proto_goTypes = []any{
	(TaskState)(0),                // 0: taskengine.v1.TaskState
	(*ScheduleTaskRequest)(nil),   // 1: taskengine.v1.ScheduleTaskRequest
	(*ScheduleTaskResponse)(nil),  // 2: taskengine.v1.ScheduleTaskResponse
	(*InspectQuotaRequest)(nil),   // 3: taskengine.v1.InspectQuotaRequest
	(*InspectQuotaResponse)(nil),  // 4: taskengine.v1.InspectQuotaResponse
	(*CancelTaskRequest)(nil),     // 5: taskengine.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),    // 6: taskengine.v1.CancelTaskResponse
	(*GetTaskStatusRequest)(nil),  // 7: taskengine.v1.GetTaskStatusRequest
	(*GetTaskStatusResponse)(nil), // 8: taskengine.v1.GetTaskStatusResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_taskengine_v1_taskengine_proto_depIdxs = []int32{
	9, // 0: taskengine.v1.ScheduleTaskRequest.schedule_time:type_name -> google.protobuf.Timestamp
	0, // 1: taskengine.v1.GetTaskStatusResponse.state:type_name -> taskengine.v1.TaskState
	9, // 2: taskengine.v1.GetTaskStatusResponse.next_run:type_name -> google.protobuf.Timestamp
	1, // 3: taskengine.v1.TaskEngineService.ScheduleTask:input_type -> taskengine.v1.ScheduleTaskRequest
	3, // 4: taskengine.v1.TaskEngineService.InspectQuota:input_type -> taskengine.v1.InspectQuotaRequest
	5, // 5: taskengine.v1.TaskEngineService.CancelTask:input_type -> taskengine.v1.CancelTaskRequest
	7, // 6: taskengine.v1.TaskEngineService.GetTaskStatus:input_type -> taskengine.v1.GetTaskStatusRequest
	2, // 7: taskengine.v1.TaskEngineService.ScheduleTask:output_type -> taskengine.v1.ScheduleTaskResponse
	4, // 8: taskengine.v1.TaskEngineService.InspectQuota:output_type -> taskengine.v1.InspectQuotaResponse
	6, // 9: taskengine.v1.TaskEngineService.CancelTask:output_type -> taskengine.v1.CancelTaskResponse
	8, // 10: taskengine.v1.TaskEngineService.GetTaskStatus:output_type -> taskengine.v1.GetTaskStatusResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_taskengine_v1_taskengine_proto_init() }
func file_taskengine_v1_taskengine_proto_init() {
	if File_taskengine_v1_taskengine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskengine_v1_taskengine_proto_rawDesc), len(file_taskengine_v1_taskengine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taskengine_v1_taskengine_proto_goTypes,
		DependencyIndexes: file_taskengine_v1_taskengine_proto_depIdxs,
		EnumInfos:         file_taskengine_v1_taskengine_proto_enumTypes,
		MessageInfos:      file_taskengine_v1_taskengine_proto_msgTypes,
	}.Build()
	File_taskengine_v1_taskengine_proto = out.File
	file_taskengine_v1_taskengine_proto_goTypes = nil
	file_taskengine_v1_taskengine_proto_depIdxs = nil
}
