// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: taskengine/v1/taskengine.proto

package taskenginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskEngineService_ScheduleTask_FullMethodName  = "/taskengine.v1.TaskEngineService/ScheduleTask"
	TaskEngineService_InspectQuota_FullMethodName  = "/taskengine.v1.TaskEngineService/InspectQuota"
	TaskEngineService_CancelTask_FullMethodName    = "/taskengine.v1.TaskEngineService/CancelTask"
	TaskEngineService_GetTaskStatus_FullMethodName = "/taskengine.v1.TaskEngineService/GetTaskStatus"
)

// TaskEngineServiceClient is the client API for TaskEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskEngineService provides distributed task scheduling with dual-sided (ingress and egress) rate limiting.
type TaskEngineServiceClient interface {
	// Schedule a new task with rate-limiting and sharding guarantees
	ScheduleTask(ctx context.Context, in *ScheduleTaskRequest, opts ...grpc.CallOption) (*ScheduleTaskResponse, error)
	// Inspect the current rate limit quota for a given key without consuming tokens
	InspectQuota(ctx context.Context, in *InspectQuotaRequest, opts ...grpc.CallOption) (*InspectQuotaResponse, error)
	// Cancel a scheduled task by ID
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
	// Retrieve current task details and status
	GetTaskStatus(ctx context.Context, in *GetTaskStatusRequest, opts ...grpc.CallOption) (*GetTaskStatusResponse, error)
}

type taskEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskEngineServiceClient(cc grpc.ClientConnInterface) TaskEngineServiceClient {
	return &taskEngineServiceClient{cc}
}

func (c *taskEngineServiceClient) ScheduleTask(ctx context.Context, in *ScheduleTaskRequest, opts ...grpc.CallOption) (*ScheduleTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleTaskResponse)
	err := c.cc.Invoke(ctx, TaskEngineService_ScheduleTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskEngineServiceClient) InspectQuota(ctx context.Context, in *InspectQuotaRequest, opts ...grpc.CallOption) (*InspectQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectQuotaResponse)
	err := c.cc.Invoke(ctx, TaskEngineService_InspectQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskEngineServiceClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, TaskEngineService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskEngineServiceClient) GetTaskStatus(ctx context.Context, in *GetTaskStatusRequest, opts ...grpc.CallOption) (*GetTaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskStatusResponse)
	err := c.cc.Invoke(ctx, TaskEngineService_GetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskEngineServiceServer is the server API for TaskEngineService service.
// All implementations must embed UnimplementedTaskEngineServiceServer
// for forward compatibility.
//
// TaskEngineService provides distributed task scheduling with dual-sided (ingress and egress) rate limiting.
type TaskEngineServiceServer interface {
	// Schedule a new task with rate-limiting and sharding guarantees
	ScheduleTask(context.Context, *ScheduleTaskRequest) (*ScheduleTaskResponse, error)
	// Inspect the current rate limit quota for a given key without consuming tokens
	InspectQuota(context.Context, *InspectQuotaRequest) (*InspectQuotaResponse, error)
	// Cancel a scheduled task by ID
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	// Retrieve current task details and status
	GetTaskStatus(context.Context, *GetTaskStatusRequest) (*GetTaskStatusResponse, error)
	mustEmbedUnimplementedTaskEngineServiceServer()
}

// UnimplementedTaskEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskEngineServiceServer struct{}

func (UnimplementedTaskEngineServiceServer) ScheduleTask(context.Context, *ScheduleTaskRequest) (*ScheduleTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleTask not implemented")
}
func (UnimplementedTaskEngineServiceServer) InspectQuota(context.Context, *InspectQuotaRequest) (*InspectQuotaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectQuota not implemented")
}
func (UnimplementedTaskEngineServiceServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedTaskEngineServiceServer) GetTaskStatus(context.Context, *GetTaskStatusRequest) (*GetTaskStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedTaskEngineServiceServer) mustEmbedUnimplementedTaskEngineServiceServer() {}
func (UnimplementedTaskEngineServiceServer) testEmbeddedByValue()                           {}

// UnsafeTaskEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskEngineServiceServer will
// result in compilation errors.
type UnsafeTaskEngineServiceServer interface {
	mustEmbedUnimplementedTaskEngineServiceServer()
}

func RegisterTaskEngineServiceServer(s grpc.ServiceRegistrar, srv TaskEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskEngineService_ServiceDesc, srv)
}

func _TaskEngineService_ScheduleTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskEngineServiceServer).ScheduleTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskEngineService_ScheduleTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskEngineServiceServer).ScheduleTask(ctx, req.(*ScheduleTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskEngineService_InspectQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskEngineServiceServer).InspectQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskEngineService_InspectQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskEngineServiceServer).InspectQuota(ctx, req.(*InspectQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskEngineService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskEngineServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskEngineService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskEngineServiceServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskEngineService_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskEngineServiceServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskEngineService_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskEngineServiceServer).GetTaskStatus(ctx, req.(*GetTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskEngineService_ServiceDesc is the grpc.ServiceDesc for TaskEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taskengine.v1.TaskEngineService",
	HandlerType: (*TaskEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleTask",
			Handler:    _TaskEngineService_ScheduleTask_Handler,
		},
		{
			MethodName: "InspectQuota",
			Handler:    _TaskEngineService_InspectQuota_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _TaskEngineService_CancelTask_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _TaskEngineService_GetTaskStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "taskengine/v1/taskengine.proto",
}
